#!/usr/bin/env bash
#
# Pre-commit hook to check if CHANGELOG.md has been included
# when the project root or relevant module has been edited.
#
# If it has been included, the latest version is compared
# against the previous version by stripping all leading zeros
# and comparing them. If it is greater it goes on to check
# that the latest change's date is the current date (i.e. today).
# If any of these tests fail the script exits and cancels the
# commit.
#
# To bypass this validation add the `--no-verify` or `-n` flag:
# 		`git commit --no-verify ...`

# Get names of staged files being committed. If being run as
# a git hook, take the result of git diff. If not, receive
# the edited files from the CLI arguments provided.
if [[ "${#}" -eq 0 ]]
then
    STAGED_FILES=($(git diff --cached --name-only)) # Local git hook
else
    STAGED_FILES=("${@}") # Github workflow passes arguments
fi

if [[ "${#STAGED_FILES[@]}" == 0 ]]
then
    echo "No files modified"
    exit 0
fi

ROOT_EDITED=0
ROOT_CHANGELOG_INCLUDED=0
MODULES_EDITED=()
CHANGELOG_ERRORS_FOUND=0
IGNORE_DIRS=(".github" ".githooks" "docs" "bin")

# Loop through staged files
for file in "${STAGED_FILES[@]}"
do
    # Check if files are in root directory
    if [[ "${file}" =~ /+ ]]
    then
        root=0
    else
        ROOT_EDITED=1
        root=1
    fi
    # Check for CHANGELOG.md in root directory
    if [[ "${root}" == 1 && "${file}" =~ CHANGELOG.md ]]
    then
        ROOT_CHANGELOG_INCLUDED=1
    fi
    if [[ "${root}" == 0 ]]
    then
        module="$(echo "${file}" | sed 's/\/.*//')"
        # Only add to modules list if not already present
        if [[ ! "${MODULES_EDITED[*]}" =~ ${module} ]]
        then
            [[ ! "${IGNORE_DIRS[*]}" =~ ${module} ]] && MODULES_EDITED+=("${module}")
        fi
    fi
done

# Check if the root directory has been changed and if the
# root CHANGELOG.md file was included in the commit
if [[ "${ROOT_EDITED}" == 1 && "${ROOT_CHANGELOG_INCLUDED}" == 0 ]]
then
    printf 'Root changelog not included\n\n' >&2
    CHANGELOG_ERRORS_FOUND=1
fi

# Check that for each module edited the CHANGELOG.md file
# was included in the commit
MODULES_MISSING_CHANGELOG=()
CHANGELOG_FILES=() # Store included changelog locations
if [[ "${#MODULES_EDITED[@]}" != 0 ]]
then
    # Loop through edited modules checking for CHANGELOG.md
    for module in "${MODULES_EDITED[@]}"
    do
        MODULE_CHANGELOG_INCLUDED=0
        for file in "${STAGED_FILES[@]}"
        do
            if [[ "${file}" =~ "${module}"/* ]]
            then
                if [[ "${file}" =~ CHANGELOG.md ]]
                then
                    # Add full file path to account for CHANGELOG location
                    # inconsistencies module root or doc/docs subdir
                    CHANGELOG_FILES+=("${file}")
                    MODULE_CHANGELOG_INCLUDED=1
                fi
            fi
        done
        # Add modules missing CHANGELOG.md to array
        if [[ "${MODULE_CHANGELOG_INCLUDED}" == 0 ]]
        then
            MODULES_MISSING_CHANGELOG+=("${module}")
        fi
        MODULE_CHANGELOG_INCLUDED=0
    done
fi

# Print error messages and prepare exit for modules missing changelogs
if [[ "${#MODULES_MISSING_CHANGELOG[@]}" != 0 ]]
then
    for module in "${MODULES_MISSING_CHANGELOG[@]}"
    do
        printf 'Missing changelog in module: %s/\n\n' "${module}" >&2
        CHANGELOG_ERRORS_FOUND=1
	done
fi

# Check version numbers and dates in changelogs provided
for log in "${CHANGELOG_FILES[@]}"
do
    # sed using BRE expression for portability
    head_versions=($(sed -n 's/^.*\(\[[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\]\) - \([0-9][0-9]*-[0-9][0-9]*-[0-9][0-9]*\).*$/\1 \2/p' "${log}" | head -n2))
    # Get latest and previous versions and strip any leading 0s
    # and check the latest version is greater than the previous
    latest_version=$(($(echo "${head_versions[0]:1:-1}" | sed 's/\.//g' | sed 's/^0*//')+0))
    previous_version=$(($(echo "${head_versions[2]:1:-1}" | sed 's/\.//g' | sed 's/^0*//')+0))
    if [[ "${latest_version}" -le "${previous_version}" ]]
    then
        printf 'Latest version in %s is incorrect.\nLatest: %s, Previous: %s\n\n' "${log}" "${head_versions[0]}" "${head_versions[2]}" >&2
        CHANGELOG_ERRORS_FOUND=1
    fi
    # compare date in string format YY-mm-dd
    latest_date="${head_versions[1]}"
    current_date=$(date +'%Y-%m-%d')
    # Check latest date in changelog is current date
    if [[ "${latest_date}" != "${current_date}" ]]
    then
        printf 'Latest date in %s is incorrect.\nLatest: %s, Current: %s\n\n' "${log}" "${head_versions[1]}" "${current_date}" >&2
        CHANGELOG_ERRORS_FOUND=1
    fi
done

# Exit with error code 1 after all error messages have been
# printed to stderr. If no errors detected exit with code 0
if [[ "${CHANGELOG_ERRORS_FOUND}" == 1 ]]
then
    printf 'Changelog verification failed. See error messages for more detail.\n' >&2
    exit 1
fi
