openapi: 3.0.3
servers:
  - url: "http://localhost:50832"
info:
  description: >-
    This is the API definition Pocket Network Node RPC interface.


    Pocket is a distributed network that relays data requests and responses to and from any blockchain system.


    Pocket verifies all relayed data and proportionally rewards the participating nodes with POKT.
  version: 1.0.0
  title: Pocket Network
  termsOfService: "https://pokt.network/terms/"
  contact:
    email: hola@pokt.network
  license:
    name: MIT License
    url: "https://github.com/pokt-network/pocket/blob/main/LICENSE"
tags:
  - name: version
    description: Version of the Pocket API
  - name: health
    description: Liveness of the Pocket API node
  - name: client
    description: Dispatch and relay services
  - name: consensus
    description: Consensus related methods
paths:
  /v1/health:
    get:
      tags:
        - health
      summary: Get the liveness of the Pocket API node
      responses:
        "200":
          description: Healthy
        "404":
          description: Unhealthy - Unreachable
        "500":
          description: Unhealthy - Server Error
  /v1/version:
    get:
      tags:
        - version
      summary: Get the current version of the Pocket Network API
      responses:
        default:
          description: Default response
          content:
            text/plain:
              schema:
                type: string
                example: 1.0.0
  /v1/consensus/state:
    get:
      tags:
        - consensus
      summary: Gets the current height, round and step
      responses:
        default:
          description: Default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsensusState"
              example: { "height": 75016, "round": 0, "step": 3 }
  /v1/client/broadcast_tx_sync:
    post:
      tags:
        - client
      summary: Broadcast raw transaction bytes
      requestBody:
        description: Raw transaction to be broadcasted
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RawTXRequest"
      responses:
        "200":
          description: Transaction added to the mempool without errors
        "400":
          description: Bad request
          content:
            text/plain:
              example: "description of failure"
        "500":
          description: An error occurred while adding the transaction to the mempool
          content:
            text/plain:
              example: "description of failure"

  /v1/p2p/staked_actors_address_book:
    get:
      tags:
        - p2p
      summary: Returns the protocol actor address book
      parameters:
        - in: query
          name: height
          required: false
          schema:
            type: integer
            format: int64
            minimum: 0
          description: The height the query will be executed on. By default it uses the current height of the consensus module. This may be the latest height if synched or an earlier height if synching.
        - in: query
          name: actor_type
          required: false
          schema:
            $ref: "#/components/schemas/ActorTypesEnum"
          description: The type of actor the address book will be populated with. By default it returns an address book for all protocol actors supported by the blockchain

      responses:
        "200":
          description: Staked actors response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/P2PStakedActorsResponse"

        "400":
          description: Bad request
          content:
            text/plain:
              example: "description of failure"
        "500":
          description: An error occurred while retrieving the staked actors address book
          content:
            text/plain:
              example: "description of failure"

externalDocs:
  description: Find out more about Pocket Network
  url: "https://pokt.network"
components:
  schemas:
    RawTXRequest:
      type: object
      required:
        - address
        - raw_hex_bytes
      properties:
        address:
          type: string
        raw_hex_bytes:
          type: string
    ConsensusState:
      type: object
      required:
        - height
        - round
        - step
      properties:
        height:
          type: integer
          format: int64
        round:
          type: integer
          format: int64
        step:
          type: integer
          format: int64
    Actor:
      type: object
      required:
        - type
        - address
        - public_key
        - service_url
      properties:
        type:
          $ref: "#/components/schemas/ActorTypesEnum"
        address:
          type: string
        public_key:
          type: string
        service_url:
          type: string

    P2PStakedActorsResponse:
      type: object
      required:
        - actors
        - height
      properties:
        actors:
          type: "array"
          items:
            $ref: "#/components/schemas/Actor"
        height:
          type: integer
          format: int64

    ActorTypesEnum:
      type: string
      enum:
        - validator
        - servicer
        - fisherman
        - application

  securitySchemes: {}
  links: {}
  callbacks: {}
security: []
