// Package rpc provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package rpc

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// RawTXRequest defines model for RawTXRequest.
type RawTXRequest struct {
	Address     string `json:"address"`
	RawHexBytes string `json:"raw_hex_bytes"`
}

// PostV1ClientBroadcastTxSyncJSONBody defines parameters for PostV1ClientBroadcastTxSync.
type PostV1ClientBroadcastTxSyncJSONBody = RawTXRequest

// PostV1ClientBroadcastTxSyncJSONRequestBody defines body for PostV1ClientBroadcastTxSync for application/json ContentType.
type PostV1ClientBroadcastTxSyncJSONRequestBody = PostV1ClientBroadcastTxSyncJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Relays a raw transaction
	// (POST /v1/client/broadcast_tx_sync)
	PostV1ClientBroadcastTxSync(ctx echo.Context) error
	// Get the liveness of the Pocket API node
	// (GET /v1/health)
	GetV1Health(ctx echo.Context) error
	// Get the current version of the Pocket Network API
	// (GET /v1/version)
	GetV1Version(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostV1ClientBroadcastTxSync converts echo context to params.
func (w *ServerInterfaceWrapper) PostV1ClientBroadcastTxSync(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostV1ClientBroadcastTxSync(ctx)
	return err
}

// GetV1Health converts echo context to params.
func (w *ServerInterfaceWrapper) GetV1Health(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetV1Health(ctx)
	return err
}

// GetV1Version converts echo context to params.
func (w *ServerInterfaceWrapper) GetV1Version(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetV1Version(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v1/client/broadcast_tx_sync", wrapper.PostV1ClientBroadcastTxSync)
	router.GET(baseURL+"/v1/health", wrapper.GetV1Health)
	router.GET(baseURL+"/v1/version", wrapper.GetV1Version)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xV3W/bNhD/Vwhuj67lNC0w6Gn5Whcg64IkDQasQXAizxYbimTJk20h8P8+HCUnip10",
	"e9gbbd4H7/dxepTKN8E7dJRk+SiTqrGBfLyC1c1fV/i9xUT8O0QfMJLBfAtaR0z5SF1AWcpE0biF3Exk",
	"hNV9jev7qiN8LYJD8HtrImpZ/v1UajfxbrJN9NU3VCQ3nIlrwujAnnqVa2tMKppAxjtZyt+M08K3JBof",
	"UUDFx0uvHpDEZ6SVjw9yIttoZSlropDKogj+gaZuuNxMpHFzz4WVdwQqj44NmJziLfy6G//yATe1ScIk",
	"QTWKo8tzoXFunOHLnXcIxS+8ujwRCqydfnVf3RBgkgChDaNVtYRaDM0E1UAiooUuCQ0EIvbsJAFOi4gp",
	"eJcwCfL5j3n0jQDXicp69aBqME6kLhE2425LjGZuMAmwti+Ouq/ONZh0H/n5YG0nIq4g6n66AJGMMgHI",
	"uIVwXmMSK0O1cEBmiULFLpBfRAi1UYL8A7o0lRNpjUKXkHF10DC9f5zfiIvh3112Fobqtpoq32Si3g1Y",
	"FCG/vqisr4oGjCsuzk/OPl+fMSOEsUl/zq8xLo3CN6guclQhJ5IMWY7a08kSY+pZPZjOpjMu7QM6CEaW",
	"8nA6mx7KiQxAdRZisTwolDXoqKiiB60g0T2t71PnVPaP733ELgJG9FznpoluD05y3vE27WZ9zUm9TTDR",
	"sdfdVpLochUIwRqV6xTfEj9ya14+/RxxLkv5U/Hs7mKwdvHC19lSLxV8BStBEVwClWVLXlS4VYYcW5di",
	"i9nLg/C48/vZbN+VN6NyoDVqLsoaarAJ3tusG7YqxuhjYqA/9HVGExOuqQgWTJ4V19CETNuolfBzMQdj",
	"24hyf7Bj0FvHcIeP/3+HI9dPILxSbYyoxao2Fnlm9ghPvIPsCIRcL7VNA7FjGnqfg4gv+WDBwiLx4uzV",
	"Ju84kdVXI1iq+e0LfEVqn5BuD37vY/4La31o17PxYf/+i+sbduKd+OIigqqhsjjC9u149iZGccZo7Qz+",
	"CSnDYs0SHabEkPPvwZ68VHnZjHAY5n7C4cm3PwLidgjaQULjHFpLP1TGs8+eNdJviMnep25PI6d9g6d1",
	"/cb0WT8ur+c06G4EwvYbcnR5PsJhO/ddbpsyxHzxONqpZVFYr8DWPlH5cfbL4Xu5uXsqsUvZ7avd+67D",
	"8t423Ux2ky/+lcChxMDffoVTkwKQqofvm4VOpH6pp+fswQWbu80/AQAA//9GztJFzQgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
