// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/shared/modules/persistance_module.go

// Package mock_modules is a generated GoMock package.
package mock_modules

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	context "pocket/consensus/pkg/shared/context"
	modules "pocket/consensus/pkg/shared/modules"
)

// MockPersistanceModule is a mock of PersistanceModule interface.
type MockPersistanceModule struct {
	ctrl     *gomock.Controller
	recorder *MockPersistanceModuleMockRecorder
}

// MockPersistanceModuleMockRecorder is the mock recorder for MockPersistanceModule.
type MockPersistanceModuleMockRecorder struct {
	mock *MockPersistanceModule
}

// NewMockPersistanceModule creates a new mock instance.
func NewMockPersistanceModule(ctrl *gomock.Controller) *MockPersistanceModule {
	mock := &MockPersistanceModule{ctrl: ctrl}
	mock.recorder = &MockPersistanceModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistanceModule) EXPECT() *MockPersistanceModuleMockRecorder {
	return m.recorder
}

// GetBlockHash mocks base method.
func (m *MockPersistanceModule) GetBlockHash(height uint64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", height)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockPersistanceModuleMockRecorder) GetBlockHash(height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockPersistanceModule)(nil).GetBlockHash), height)
}

// GetLatestBlockHeight mocks base method.
func (m *MockPersistanceModule) GetLatestBlockHeight() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlockHeight")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlockHeight indicates an expected call of GetLatestBlockHeight.
func (mr *MockPersistanceModuleMockRecorder) GetLatestBlockHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlockHeight", reflect.TypeOf((*MockPersistanceModule)(nil).GetLatestBlockHeight))
}

// GetPocketBusMod mocks base method.
func (m *MockPersistanceModule) GetPocketBusMod() modules.PocketBusModule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPocketBusMod")
	ret0, _ := ret[0].(modules.PocketBusModule)
	return ret0
}

// GetPocketBusMod indicates an expected call of GetPocketBusMod.
func (mr *MockPersistanceModuleMockRecorder) GetPocketBusMod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPocketBusMod", reflect.TypeOf((*MockPersistanceModule)(nil).GetPocketBusMod))
}

// SetPocketBusMod mocks base method.
func (m *MockPersistanceModule) SetPocketBusMod(arg0 modules.PocketBusModule) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPocketBusMod", arg0)
}

// SetPocketBusMod indicates an expected call of SetPocketBusMod.
func (mr *MockPersistanceModuleMockRecorder) SetPocketBusMod(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPocketBusMod", reflect.TypeOf((*MockPersistanceModule)(nil).SetPocketBusMod), arg0)
}

// Start mocks base method.
func (m *MockPersistanceModule) Start(arg0 *context.PocketContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockPersistanceModuleMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPersistanceModule)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockPersistanceModule) Stop(arg0 *context.PocketContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockPersistanceModuleMockRecorder) Stop(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPersistanceModule)(nil).Stop), arg0)
}
