// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: block_cons_temp.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO(olshansky): Work with andrew to generalize and merge type with the corresponding one in utility.
type BlockConsensusTemp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeader  *BlockHeaderConsensusTemp `protobuf:"bytes,1,opt,name=BlockHeader,proto3" json:"BlockHeader,omitempty"`
	Transactions [][]byte                  `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
}

func (x *BlockConsensusTemp) Reset() {
	*x = BlockConsensusTemp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_cons_temp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockConsensusTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockConsensusTemp) ProtoMessage() {}

func (x *BlockConsensusTemp) ProtoReflect() protoreflect.Message {
	mi := &file_block_cons_temp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockConsensusTemp.ProtoReflect.Descriptor instead.
func (*BlockConsensusTemp) Descriptor() ([]byte, []int) {
	return file_block_cons_temp_proto_rawDescGZIP(), []int{0}
}

func (x *BlockConsensusTemp) GetBlockHeader() *BlockHeaderConsensusTemp {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *BlockConsensusTemp) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// TODO(olshansky): Work with andrew to generalize and merge type with the corresponding one in utility.
type BlockHeaderConsensusTemp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height          int64  `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Hash            []byte `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	NumTxs          uint32 `protobuf:"varint,3,opt,name=NumTxs,proto3" json:"NumTxs,omitempty"`
	LastBlockHash   string `protobuf:"bytes,4,opt,name=LastBlockHash,proto3" json:"LastBlockHash,omitempty"`
	ProposerAddress []byte `protobuf:"bytes,5,opt,name=ProposerAddress,proto3" json:"ProposerAddress,omitempty"`
	// TODO(discuss): The `QuorumCertificate` structure contains the `Block` inside of it so we end up with a two way relationship?
	QuorumCertificate []byte `protobuf:"bytes,6,opt,name=QuorumCertificate,proto3" json:"QuorumCertificate,omitempty"`
}

func (x *BlockHeaderConsensusTemp) Reset() {
	*x = BlockHeaderConsensusTemp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_cons_temp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeaderConsensusTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeaderConsensusTemp) ProtoMessage() {}

func (x *BlockHeaderConsensusTemp) ProtoReflect() protoreflect.Message {
	mi := &file_block_cons_temp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeaderConsensusTemp.ProtoReflect.Descriptor instead.
func (*BlockHeaderConsensusTemp) Descriptor() ([]byte, []int) {
	return file_block_cons_temp_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeaderConsensusTemp) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeaderConsensusTemp) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockHeaderConsensusTemp) GetNumTxs() uint32 {
	if x != nil {
		return x.NumTxs
	}
	return 0
}

func (x *BlockHeaderConsensusTemp) GetLastBlockHash() string {
	if x != nil {
		return x.LastBlockHash
	}
	return ""
}

func (x *BlockHeaderConsensusTemp) GetProposerAddress() []byte {
	if x != nil {
		return x.ProposerAddress
	}
	return nil
}

func (x *BlockHeaderConsensusTemp) GetQuorumCertificate() []byte {
	if x != nil {
		return x.QuorumCertificate
	}
	return nil
}

var File_block_cons_temp_proto protoreflect.FileDescriptor

var file_block_cons_temp_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73,
	0x75, 0x73, 0x22, 0x7f, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x73, 0x65,
	0x6e, 0x73, 0x75, 0x73, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x45, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x54, 0x65,
	0x6d, 0x70, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x22, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0xdc, 0x01, 0x0a, 0x18, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x54, 0x65, 0x6d, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x4e, 0x75, 0x6d, 0x54, 0x78, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x4e, 0x75,
	0x6d, 0x54, 0x78, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4c, 0x61, 0x73,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x11, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_block_cons_temp_proto_rawDescOnce sync.Once
	file_block_cons_temp_proto_rawDescData = file_block_cons_temp_proto_rawDesc
)

func file_block_cons_temp_proto_rawDescGZIP() []byte {
	file_block_cons_temp_proto_rawDescOnce.Do(func() {
		file_block_cons_temp_proto_rawDescData = protoimpl.X.CompressGZIP(file_block_cons_temp_proto_rawDescData)
	})
	return file_block_cons_temp_proto_rawDescData
}

var file_block_cons_temp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_block_cons_temp_proto_goTypes = []interface{}{
	(*BlockConsensusTemp)(nil),       // 0: consensus.BlockConsensusTemp
	(*BlockHeaderConsensusTemp)(nil), // 1: consensus.BlockHeaderConsensusTemp
}
var file_block_cons_temp_proto_depIdxs = []int32{
	1, // 0: consensus.BlockConsensusTemp.BlockHeader:type_name -> consensus.BlockHeaderConsensusTemp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_block_cons_temp_proto_init() }
func file_block_cons_temp_proto_init() {
	if File_block_cons_temp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_block_cons_temp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockConsensusTemp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_cons_temp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeaderConsensusTemp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_block_cons_temp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_cons_temp_proto_goTypes,
		DependencyIndexes: file_block_cons_temp_proto_depIdxs,
		MessageInfos:      file_block_cons_temp_proto_msgTypes,
	}.Build()
	File_block_cons_temp_proto = out.File
	file_block_cons_temp_proto_rawDesc = nil
	file_block_cons_temp_proto_goTypes = nil
	file_block_cons_temp_proto_depIdxs = nil
}
