// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: debug_message.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebugMessageAction int32

const (
	DebugMessageAction_DEBUG_ACTION_UNKNOWN                   DebugMessageAction = 0
	DebugMessageAction_DEBUG_CONSENSUS_RESET_TO_GENESIS       DebugMessageAction = 1
	DebugMessageAction_DEBUG_CONSENSUS_PRINT_NODE_STATE       DebugMessageAction = 2
	DebugMessageAction_DEBUG_CONSENSUS_TRIGGER_NEXT_VIEW      DebugMessageAction = 3
	DebugMessageAction_DEBUG_CONSENSUS_TOGGLE_PACE_MAKER_MODE DebugMessageAction = 4 // toggle between manual and automatic
)

// Enum value maps for DebugMessageAction.
var (
	DebugMessageAction_name = map[int32]string{
		0: "DEBUG_ACTION_UNKNOWN",
		1: "DEBUG_CONSENSUS_RESET_TO_GENESIS",
		2: "DEBUG_CONSENSUS_PRINT_NODE_STATE",
		3: "DEBUG_CONSENSUS_TRIGGER_NEXT_VIEW",
		4: "DEBUG_CONSENSUS_TOGGLE_PACE_MAKER_MODE",
	}
	DebugMessageAction_value = map[string]int32{
		"DEBUG_ACTION_UNKNOWN":                   0,
		"DEBUG_CONSENSUS_RESET_TO_GENESIS":       1,
		"DEBUG_CONSENSUS_PRINT_NODE_STATE":       2,
		"DEBUG_CONSENSUS_TRIGGER_NEXT_VIEW":      3,
		"DEBUG_CONSENSUS_TOGGLE_PACE_MAKER_MODE": 4,
	}
)

func (x DebugMessageAction) Enum() *DebugMessageAction {
	p := new(DebugMessageAction)
	*p = x
	return p
}

func (x DebugMessageAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DebugMessageAction) Descriptor() protoreflect.EnumDescriptor {
	return file_debug_message_proto_enumTypes[0].Descriptor()
}

func (DebugMessageAction) Type() protoreflect.EnumType {
	return &file_debug_message_proto_enumTypes[0]
}

func (x DebugMessageAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DebugMessageAction.Descriptor instead.
func (DebugMessageAction) EnumDescriptor() ([]byte, []int) {
	return file_debug_message_proto_rawDescGZIP(), []int{0}
}

type DebugMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  DebugMessageAction `protobuf:"varint,1,opt,name=action,proto3,enum=consensus.DebugMessageAction" json:"action,omitempty"`
	Message *anypb.Any         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DebugMessage) Reset() {
	*x = DebugMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_debug_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugMessage) ProtoMessage() {}

func (x *DebugMessage) ProtoReflect() protoreflect.Message {
	mi := &file_debug_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugMessage.ProtoReflect.Descriptor instead.
func (*DebugMessage) Descriptor() ([]byte, []int) {
	return file_debug_message_proto_rawDescGZIP(), []int{0}
}

func (x *DebugMessage) GetAction() DebugMessageAction {
	if x != nil {
		return x.Action
	}
	return DebugMessageAction_DEBUG_ACTION_UNKNOWN
}

func (x *DebugMessage) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_debug_message_proto protoreflect.FileDescriptor

var file_debug_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0c, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2a, 0xcd, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x45, 0x42,
	0x55, 0x47, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20, 0x44, 0x45, 0x42, 0x55, 0x47, 0x5f, 0x43, 0x4f, 0x4e,
	0x53, 0x45, 0x4e, 0x53, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x54, 0x5f, 0x54, 0x4f, 0x5f,
	0x47, 0x45, 0x4e, 0x45, 0x53, 0x49, 0x53, 0x10, 0x01, 0x12, 0x24, 0x0a, 0x20, 0x44, 0x45, 0x42,
	0x55, 0x47, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x45, 0x4e, 0x53, 0x55, 0x53, 0x5f, 0x50, 0x52, 0x49,
	0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12,
	0x25, 0x0a, 0x21, 0x44, 0x45, 0x42, 0x55, 0x47, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x45, 0x4e, 0x53,
	0x55, 0x53, 0x5f, 0x54, 0x52, 0x49, 0x47, 0x47, 0x45, 0x52, 0x5f, 0x4e, 0x45, 0x58, 0x54, 0x5f,
	0x56, 0x49, 0x45, 0x57, 0x10, 0x03, 0x12, 0x2a, 0x0a, 0x26, 0x44, 0x45, 0x42, 0x55, 0x47, 0x5f,
	0x43, 0x4f, 0x4e, 0x53, 0x45, 0x4e, 0x53, 0x55, 0x53, 0x5f, 0x54, 0x4f, 0x47, 0x47, 0x4c, 0x45,
	0x5f, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x4d, 0x41, 0x4b, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x44, 0x45,
	0x10, 0x04, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_debug_message_proto_rawDescOnce sync.Once
	file_debug_message_proto_rawDescData = file_debug_message_proto_rawDesc
)

func file_debug_message_proto_rawDescGZIP() []byte {
	file_debug_message_proto_rawDescOnce.Do(func() {
		file_debug_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_debug_message_proto_rawDescData)
	})
	return file_debug_message_proto_rawDescData
}

var file_debug_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_debug_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_debug_message_proto_goTypes = []interface{}{
	(DebugMessageAction)(0), // 0: consensus.DebugMessageAction
	(*DebugMessage)(nil),    // 1: consensus.DebugMessage
	(*anypb.Any)(nil),       // 2: google.protobuf.Any
}
var file_debug_message_proto_depIdxs = []int32{
	0, // 0: consensus.DebugMessage.action:type_name -> consensus.DebugMessageAction
	2, // 1: consensus.DebugMessage.message:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_debug_message_proto_init() }
func file_debug_message_proto_init() {
	if File_debug_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_debug_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_debug_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_debug_message_proto_goTypes,
		DependencyIndexes: file_debug_message_proto_depIdxs,
		EnumInfos:         file_debug_message_proto_enumTypes,
		MessageInfos:      file_debug_message_proto_msgTypes,
	}.Build()
	File_debug_message_proto = out.File
	file_debug_message_proto_rawDesc = nil
	file_debug_message_proto_goTypes = nil
	file_debug_message_proto_depIdxs = nil
}
