// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: unstaking.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnstakingActor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address       []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	StakeAmount   string `protobuf:"bytes,2,opt,name=StakeAmount,proto3" json:"StakeAmount,omitempty"`
	OutputAddress []byte `protobuf:"bytes,3,opt,name=OutputAddress,proto3" json:"OutputAddress,omitempty"`
}

func (x *UnstakingActor) Reset() {
	*x = UnstakingActor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unstaking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnstakingActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstakingActor) ProtoMessage() {}

func (x *UnstakingActor) ProtoReflect() protoreflect.Message {
	mi := &file_unstaking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstakingActor.ProtoReflect.Descriptor instead.
func (*UnstakingActor) Descriptor() ([]byte, []int) {
	return file_unstaking_proto_rawDescGZIP(), []int{0}
}

func (x *UnstakingActor) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UnstakingActor) GetStakeAmount() string {
	if x != nil {
		return x.StakeAmount
	}
	return ""
}

func (x *UnstakingActor) GetOutputAddress() []byte {
	if x != nil {
		return x.OutputAddress
	}
	return nil
}

type UnstakingActors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnstakingActors []*UnstakingActor `protobuf:"bytes,1,rep,name=UnstakingActors,proto3" json:"UnstakingActors,omitempty"`
}

func (x *UnstakingActors) Reset() {
	*x = UnstakingActors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unstaking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnstakingActors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstakingActors) ProtoMessage() {}

func (x *UnstakingActors) ProtoReflect() protoreflect.Message {
	mi := &file_unstaking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstakingActors.ProtoReflect.Descriptor instead.
func (*UnstakingActors) Descriptor() ([]byte, []int) {
	return file_unstaking_proto_rawDescGZIP(), []int{1}
}

func (x *UnstakingActors) GetUnstakingActors() []*UnstakingActor {
	if x != nil {
		return x.UnstakingActors
	}
	return nil
}

var File_unstaking_proto protoreflect.FileDescriptor

var file_unstaking_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x72, 0x0a, 0x0e, 0x55, 0x6e,
	0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x74, 0x61,
	0x6b, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x54,
	0x0a, 0x0f, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x12, 0x41, 0x0a, 0x0f, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x0f, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unstaking_proto_rawDescOnce sync.Once
	file_unstaking_proto_rawDescData = file_unstaking_proto_rawDesc
)

func file_unstaking_proto_rawDescGZIP() []byte {
	file_unstaking_proto_rawDescOnce.Do(func() {
		file_unstaking_proto_rawDescData = protoimpl.X.CompressGZIP(file_unstaking_proto_rawDescData)
	})
	return file_unstaking_proto_rawDescData
}

var file_unstaking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unstaking_proto_goTypes = []interface{}{
	(*UnstakingActor)(nil),  // 0: utility.UnstakingActor
	(*UnstakingActors)(nil), // 1: utility.UnstakingActors
}
var file_unstaking_proto_depIdxs = []int32{
	0, // 0: utility.UnstakingActors.UnstakingActors:type_name -> utility.UnstakingActor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_unstaking_proto_init() }
func file_unstaking_proto_init() {
	if File_unstaking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unstaking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnstakingActor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unstaking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnstakingActors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unstaking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unstaking_proto_goTypes,
		DependencyIndexes: file_unstaking_proto_depIdxs,
		MessageInfos:      file_unstaking_proto_msgTypes,
	}.Build()
	File_unstaking_proto = out.File
	file_unstaking_proto_rawDesc = nil
	file_unstaking_proto_goTypes = nil
	file_unstaking_proto_depIdxs = nil
}
