package test_artifacts

import (
	"github.com/pokt-network/pocket/shared/crypto"
	"github.com/pokt-network/pocket/shared/types"
	"github.com/pokt-network/pocket/shared/types/genesis"
	"math/big"
)

var (
	// NOTE: this is for fun illustration purposes... The addresses begin with DA0, DA0, and FEE :)
	// Of course, in a production network the params / owners must be set in the genesis file
	DefaultParamsOwner, _          = crypto.NewPrivateKey("ff538589deb7f28bbce1ba68b37d2efc0eaa03204b36513cf88422a875559e38d6cbe0430ddd85a5e48e0c99ef3dea47bf0d1a83c6e6ad1640f72201dc8a0120")
	DefaultDAOPool, _              = crypto.NewPrivateKey("b1dfb25a67dadf9cdd39927b86166149727649af3a3143e66e558652f8031f3faacaa24a69bcf2819ed97ab5ed8d1e490041e5c7ef9e1eddba8b5678f997ae58")
	DefaultFeeCollector, _         = crypto.NewPrivateKey("bdc02826b5da77b90a5d1550443b3f007725cc654c10002aa01e65a131f3464b826f8e7911fa89b4bd6659c3175114d714c60bac63acc63817c0d3a4ed2fdab8")
	DefaultFishermanStakePool, _   = crypto.NewPrivateKey("f3dd5c8ccd9a7c8d0afd36424c6fbe8ead55315086ef3d0d03ce8c7357e5e306733a711adb6fc8fbef6a3e2ac2db7842433053a23c751d19573ab85b52316f67")
	DefaultServiceNodeStakePool, _ = crypto.NewPrivateKey("b4e4426ed014d5ee89949e6f60c406c328e4fce466cd25f4697a41046b34313097a8cc38033822da010422851062ae6b21b8e29d4c34193b7d8fa0f37b6593b6")
	DefaultValidatorStakePool, _   = crypto.NewPrivateKey("e0b8b7cdb33f11a8d70eb05070e53b02fe74f4499aed7b159bd2dd256e356d67664b5b682e40ee218e5feea05c2a1bb595ec15f3850c92b571cdf950b4d9ba23")
	DefaultAppStakePool, _         = crypto.NewPrivateKey("429627bac8dc322f0aeeb2b8f25b329899b7ebb9605d603b5fb74557b13357e50834e9575c19d9d7d664ec460a98abb2435ece93440eb482c87d5b7259a8d271")
)

func DefaultParams() *genesis.Params {
	return &genesis.Params{
		BlocksPerSession:                         4,
		AppMinimumStake:                          types.BigIntToString(big.NewInt(15000000000)),
		AppMaxChains:                             15,
		AppBaselineStakeRate:                     100,
		AppStakingAdjustment:                     0,
		AppUnstakingBlocks:                       2016,
		AppMinimumPauseBlocks:                    4,
		AppMaxPauseBlocks:                        672,
		ServiceNodeMinimumStake:                  types.BigIntToString(big.NewInt(15000000000)),
		ServiceNodeMaxChains:                     15,
		ServiceNodeUnstakingBlocks:               2016,
		ServiceNodeMinimumPauseBlocks:            4,
		ServiceNodeMaxPauseBlocks:                672,
		ServiceNodesPerSession:                   24,
		FishermanMinimumStake:                    types.BigIntToString(big.NewInt(15000000000)),
		FishermanMaxChains:                       15,
		FishermanUnstakingBlocks:                 2016,
		FishermanMinimumPauseBlocks:              4,
		FishermanMaxPauseBlocks:                  672,
		ValidatorMinimumStake:                    types.BigIntToString(big.NewInt(15000000000)),
		ValidatorUnstakingBlocks:                 2016,
		ValidatorMinimumPauseBlocks:              4,
		ValidatorMaxPauseBlocks:                  672,
		ValidatorMaximumMissedBlocks:             5,
		ValidatorMaxEvidenceAgeInBlocks:          8,
		ProposerPercentageOfFees:                 10,
		MissedBlocksBurnPercentage:               1,
		DoubleSignBurnPercentage:                 5,
		MessageDoubleSignFee:                     types.BigIntToString(big.NewInt(10000)),
		MessageSendFee:                           types.BigIntToString(big.NewInt(10000)),
		MessageStakeFishermanFee:                 types.BigIntToString(big.NewInt(10000)),
		MessageEditStakeFishermanFee:             types.BigIntToString(big.NewInt(10000)),
		MessageUnstakeFishermanFee:               types.BigIntToString(big.NewInt(10000)),
		MessagePauseFishermanFee:                 types.BigIntToString(big.NewInt(10000)),
		MessageUnpauseFishermanFee:               types.BigIntToString(big.NewInt(10000)),
		MessageFishermanPauseServiceNodeFee:      types.BigIntToString(big.NewInt(10000)),
		MessageTestScoreFee:                      types.BigIntToString(big.NewInt(10000)),
		MessageProveTestScoreFee:                 types.BigIntToString(big.NewInt(10000)),
		MessageStakeAppFee:                       types.BigIntToString(big.NewInt(10000)),
		MessageEditStakeAppFee:                   types.BigIntToString(big.NewInt(10000)),
		MessageUnstakeAppFee:                     types.BigIntToString(big.NewInt(10000)),
		MessagePauseAppFee:                       types.BigIntToString(big.NewInt(10000)),
		MessageUnpauseAppFee:                     types.BigIntToString(big.NewInt(10000)),
		MessageStakeValidatorFee:                 types.BigIntToString(big.NewInt(10000)),
		MessageEditStakeValidatorFee:             types.BigIntToString(big.NewInt(10000)),
		MessageUnstakeValidatorFee:               types.BigIntToString(big.NewInt(10000)),
		MessagePauseValidatorFee:                 types.BigIntToString(big.NewInt(10000)),
		MessageUnpauseValidatorFee:               types.BigIntToString(big.NewInt(10000)),
		MessageStakeServiceNodeFee:               types.BigIntToString(big.NewInt(10000)),
		MessageEditStakeServiceNodeFee:           types.BigIntToString(big.NewInt(10000)),
		MessageUnstakeServiceNodeFee:             types.BigIntToString(big.NewInt(10000)),
		MessagePauseServiceNodeFee:               types.BigIntToString(big.NewInt(10000)),
		MessageUnpauseServiceNodeFee:             types.BigIntToString(big.NewInt(10000)),
		MessageChangeParameterFee:                types.BigIntToString(big.NewInt(10000)),
		AclOwner:                                 DefaultParamsOwner.Address().String(),
		BlocksPerSessionOwner:                    DefaultParamsOwner.Address().String(),
		AppMinimumStakeOwner:                     DefaultParamsOwner.Address().String(),
		AppMaxChainsOwner:                        DefaultParamsOwner.Address().String(),
		AppBaselineStakeRateOwner:                DefaultParamsOwner.Address().String(),
		AppStakingAdjustmentOwner:                DefaultParamsOwner.Address().String(),
		AppUnstakingBlocksOwner:                  DefaultParamsOwner.Address().String(),
		AppMinimumPauseBlocksOwner:               DefaultParamsOwner.Address().String(),
		AppMaxPausedBlocksOwner:                  DefaultParamsOwner.Address().String(),
		ServiceNodeMinimumStakeOwner:             DefaultParamsOwner.Address().String(),
		ServiceNodeMaxChainsOwner:                DefaultParamsOwner.Address().String(),
		ServiceNodeUnstakingBlocksOwner:          DefaultParamsOwner.Address().String(),
		ServiceNodeMinimumPauseBlocksOwner:       DefaultParamsOwner.Address().String(),
		ServiceNodeMaxPausedBlocksOwner:          DefaultParamsOwner.Address().String(),
		ServiceNodesPerSessionOwner:              DefaultParamsOwner.Address().String(),
		FishermanMinimumStakeOwner:               DefaultParamsOwner.Address().String(),
		FishermanMaxChainsOwner:                  DefaultParamsOwner.Address().String(),
		FishermanUnstakingBlocksOwner:            DefaultParamsOwner.Address().String(),
		FishermanMinimumPauseBlocksOwner:         DefaultParamsOwner.Address().String(),
		FishermanMaxPausedBlocksOwner:            DefaultParamsOwner.Address().String(),
		ValidatorMinimumStakeOwner:               DefaultParamsOwner.Address().String(),
		ValidatorUnstakingBlocksOwner:            DefaultParamsOwner.Address().String(),
		ValidatorMinimumPauseBlocksOwner:         DefaultParamsOwner.Address().String(),
		ValidatorMaxPausedBlocksOwner:            DefaultParamsOwner.Address().String(),
		ValidatorMaximumMissedBlocksOwner:        DefaultParamsOwner.Address().String(),
		ValidatorMaxEvidenceAgeInBlocksOwner:     DefaultParamsOwner.Address().String(),
		ProposerPercentageOfFeesOwner:            DefaultParamsOwner.Address().String(),
		MissedBlocksBurnPercentageOwner:          DefaultParamsOwner.Address().String(),
		DoubleSignBurnPercentageOwner:            DefaultParamsOwner.Address().String(),
		MessageDoubleSignFeeOwner:                DefaultParamsOwner.Address().String(),
		MessageSendFeeOwner:                      DefaultParamsOwner.Address().String(),
		MessageStakeFishermanFeeOwner:            DefaultParamsOwner.Address().String(),
		MessageEditStakeFishermanFeeOwner:        DefaultParamsOwner.Address().String(),
		MessageUnstakeFishermanFeeOwner:          DefaultParamsOwner.Address().String(),
		MessagePauseFishermanFeeOwner:            DefaultParamsOwner.Address().String(),
		MessageUnpauseFishermanFeeOwner:          DefaultParamsOwner.Address().String(),
		MessageFishermanPauseServiceNodeFeeOwner: DefaultParamsOwner.Address().String(),
		MessageTestScoreFeeOwner:                 DefaultParamsOwner.Address().String(),
		MessageProveTestScoreFeeOwner:            DefaultParamsOwner.Address().String(),
		MessageStakeAppFeeOwner:                  DefaultParamsOwner.Address().String(),
		MessageEditStakeAppFeeOwner:              DefaultParamsOwner.Address().String(),
		MessageUnstakeAppFeeOwner:                DefaultParamsOwner.Address().String(),
		MessagePauseAppFeeOwner:                  DefaultParamsOwner.Address().String(),
		MessageUnpauseAppFeeOwner:                DefaultParamsOwner.Address().String(),
		MessageStakeValidatorFeeOwner:            DefaultParamsOwner.Address().String(),
		MessageEditStakeValidatorFeeOwner:        DefaultParamsOwner.Address().String(),
		MessageUnstakeValidatorFeeOwner:          DefaultParamsOwner.Address().String(),
		MessagePauseValidatorFeeOwner:            DefaultParamsOwner.Address().String(),
		MessageUnpauseValidatorFeeOwner:          DefaultParamsOwner.Address().String(),
		MessageStakeServiceNodeFeeOwner:          DefaultParamsOwner.Address().String(),
		MessageEditStakeServiceNodeFeeOwner:      DefaultParamsOwner.Address().String(),
		MessageUnstakeServiceNodeFeeOwner:        DefaultParamsOwner.Address().String(),
		MessagePauseServiceNodeFeeOwner:          DefaultParamsOwner.Address().String(),
		MessageUnpauseServiceNodeFeeOwner:        DefaultParamsOwner.Address().String(),
		MessageChangeParameterFeeOwner:           DefaultParamsOwner.Address().String(),
	}
}
