// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: events.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PocketTopic int32

const (
	PocketTopic_UNKNOWN_POCKET_TOPIC    PocketTopic = 0
	PocketTopic_POCKET_NODE_TOPIC       PocketTopic = 1
	PocketTopic_CONSENSUS_MESSAGE_TOPIC PocketTopic = 2
	PocketTopic_P2P_MESSAGE_TOPIC       PocketTopic = 3
	PocketTopic_DEBUG_TOPIC             PocketTopic = 4
)

// Enum value maps for PocketTopic.
var (
	PocketTopic_name = map[int32]string{
		0: "UNKNOWN_POCKET_TOPIC",
		1: "POCKET_NODE_TOPIC",
		2: "CONSENSUS_MESSAGE_TOPIC",
		3: "P2P_MESSAGE_TOPIC",
		4: "DEBUG_TOPIC",
	}
	PocketTopic_value = map[string]int32{
		"UNKNOWN_POCKET_TOPIC":    0,
		"POCKET_NODE_TOPIC":       1,
		"CONSENSUS_MESSAGE_TOPIC": 2,
		"P2P_MESSAGE_TOPIC":       3,
		"DEBUG_TOPIC":             4,
	}
)

func (x PocketTopic) Enum() *PocketTopic {
	p := new(PocketTopic)
	*p = x
	return p
}

func (x PocketTopic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PocketTopic) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (PocketTopic) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x PocketTopic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PocketTopic.Descriptor instead.
func (PocketTopic) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type PocketEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic PocketTopic `protobuf:"varint,1,opt,name=topic,proto3,enum=pocket.PocketTopic" json:"topic,omitempty"`
	Data  *anypb.Any  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PocketEvent) Reset() {
	*x = PocketEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PocketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PocketEvent) ProtoMessage() {}

func (x *PocketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PocketEvent.ProtoReflect.Descriptor instead.
func (*PocketEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *PocketEvent) GetTopic() PocketTopic {
	if x != nil {
		return x.Topic
	}
	return PocketTopic_UNKNOWN_POCKET_TOPIC
}

func (x *PocketEvent) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

var file_events_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x62, 0x0a, 0x0b, 0x50, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x29, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x50, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x28, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x83, 0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x50, 0x4f, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x10, 0x00, 0x12,
	0x15, 0x0a, 0x11, 0x50, 0x4f, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54,
	0x4f, 0x50, 0x49, 0x43, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4e, 0x53, 0x45, 0x4e,
	0x53, 0x55, 0x53, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x4f, 0x50, 0x49,
	0x43, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x32, 0x50, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x45,
	0x42, 0x55, 0x47, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x10, 0x04, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6b, 0x74, 0x2d, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData = file_events_proto_rawDesc
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_proto_rawDescData)
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_proto_goTypes = []interface{}{
	(PocketTopic)(0),    // 0: pocket.PocketTopic
	(*PocketEvent)(nil), // 1: pocket.PocketEvent
	(*anypb.Any)(nil),   // 2: google.protobuf.Any
}
var file_events_proto_depIdxs = []int32{
	0, // 0: pocket.PocketEvent.topic:type_name -> pocket.PocketTopic
	2, // 1: pocket.PocketEvent.data:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PocketEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_rawDesc = nil
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
