apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket.fullname" . }}-genesis
  labels:
    {{- include "pocket.labels" . | nindent 4 }}
data:
  {{- if eq .Values.genesis.preProvisionedGenesis.type "devnet" }}
  genesis.json: |
    # Devnet genesis content here
  {{- else if eq .Values.genesis.preProvisionedGenesis.type "testnet" }}
  genesis.json: |
    # Testnet genesis content here
  {{- else if eq .Values.genesis.preProvisionedGenesis.type "mainnet" }}
  genesis.json: |
    # Mainnet genesis content here
  {{- end }}
