apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.service.nameOverride }}{{ .Values.service.nameOverride }}{{ else }}{{ include "pocket.fullname" . }}{{ end }}
  labels:
    {{- include "pocket.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.consensus }}
      name: consensus
    - port: {{ .Values.service.ports.rpc }}
      name: rpc
    - port: {{ .Values.service.ports.metrics }}
      name: metrics
  selector:
    {{- include "pocket.selectorLabels" . | nindent 4 }}
