package consensus

// These constants and variables are wrappers around the autogenerated protobuf types and were
// added to simply make the code in the `consensus` module more readable.

import (
	types_consensus "github.com/pokt-network/pocket/consensus/types"
)

const (
	HotstuffMessage types_consensus.ConsensusMessageType = types_consensus.ConsensusMessageType_CONSENSUS_HOTSTUFF_MESSAGE
	UtilityMessage  types_consensus.ConsensusMessageType = types_consensus.ConsensusMessageType_CONSENSUS_UTILITY_TRANSACTION
)

const (
	NewRound  types_consensus.HotstuffStep = types_consensus.HotstuffStep_HOTSTUFF_STEP_NEWROUND
	Prepare   types_consensus.HotstuffStep = types_consensus.HotstuffStep_HOTSTUFF_STEP_PREPARE
	PreCommit types_consensus.HotstuffStep = types_consensus.HotstuffStep_HOTSTUFF_STEP_PRECOMMIT
	Commit    types_consensus.HotstuffStep = types_consensus.HotstuffStep_HOTSTUFF_STEP_COMMIT
	Decide    types_consensus.HotstuffStep = types_consensus.HotstuffStep_HOTSTUFF_STEP_DECIDE
)

const (
	Propose types_consensus.HotstuffMessageType = types_consensus.HotstuffMessageType_HOTSTUFF_MESAGE_PROPOSE
	Vote    types_consensus.HotstuffMessageType = types_consensus.HotstuffMessageType_HOTSTUFF_MESSAGE_VOTE
)

var HotstuffSteps = [...]types_consensus.HotstuffStep{NewRound, Prepare, PreCommit, Commit, Decide}

var StepToString map[types_consensus.HotstuffStep]string

func init() {
	StepToString = make(map[types_consensus.HotstuffStep]string, len(types_consensus.HotstuffStep_name))
	for i, step := range types_consensus.HotstuffStep_name {
		StepToString[types_consensus.HotstuffStep(i)] = step
	}
}
