// Code generated by MockGen. DO NOT EDIT.
// Source: network.go

// Package mock_types is a generated GoMock package.
package mock_types

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/pokt-network/pocket/internal/p2p/types"
	crypto "github.com/pokt-network/pocket/internal/shared/crypto"
	modules "github.com/pokt-network/pocket/internal/shared/modules"
)

// MockNetwork is a mock of Network interface.
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork.
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance.
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return m.recorder
}

// AddPeerToAddrBook mocks base method.
func (m *MockNetwork) AddPeerToAddrBook(peer *types.NetworkPeer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPeerToAddrBook", peer)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPeerToAddrBook indicates an expected call of AddPeerToAddrBook.
func (mr *MockNetworkMockRecorder) AddPeerToAddrBook(peer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPeerToAddrBook", reflect.TypeOf((*MockNetwork)(nil).AddPeerToAddrBook), peer)
}

// GetAddrBook mocks base method.
func (m *MockNetwork) GetAddrBook() types.AddrBook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddrBook")
	ret0, _ := ret[0].(types.AddrBook)
	return ret0
}

// GetAddrBook indicates an expected call of GetAddrBook.
func (mr *MockNetworkMockRecorder) GetAddrBook() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddrBook", reflect.TypeOf((*MockNetwork)(nil).GetAddrBook))
}

// GetBus mocks base method.
func (m *MockNetwork) GetBus() modules.Bus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBus")
	ret0, _ := ret[0].(modules.Bus)
	return ret0
}

// GetBus indicates an expected call of GetBus.
func (mr *MockNetworkMockRecorder) GetBus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBus", reflect.TypeOf((*MockNetwork)(nil).GetBus))
}

// HandleNetworkData mocks base method.
func (m *MockNetwork) HandleNetworkData(data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleNetworkData", data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleNetworkData indicates an expected call of HandleNetworkData.
func (mr *MockNetworkMockRecorder) HandleNetworkData(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleNetworkData", reflect.TypeOf((*MockNetwork)(nil).HandleNetworkData), data)
}

// NetworkBroadcast mocks base method.
func (m *MockNetwork) NetworkBroadcast(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkBroadcast", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// NetworkBroadcast indicates an expected call of NetworkBroadcast.
func (mr *MockNetworkMockRecorder) NetworkBroadcast(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkBroadcast", reflect.TypeOf((*MockNetwork)(nil).NetworkBroadcast), data)
}

// NetworkSend mocks base method.
func (m *MockNetwork) NetworkSend(data []byte, address crypto.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkSend", data, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// NetworkSend indicates an expected call of NetworkSend.
func (mr *MockNetworkMockRecorder) NetworkSend(data, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkSend", reflect.TypeOf((*MockNetwork)(nil).NetworkSend), data, address)
}

// RemovePeerToAddrBook mocks base method.
func (m *MockNetwork) RemovePeerToAddrBook(peer *types.NetworkPeer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePeerToAddrBook", peer)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePeerToAddrBook indicates an expected call of RemovePeerToAddrBook.
func (mr *MockNetworkMockRecorder) RemovePeerToAddrBook(peer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePeerToAddrBook", reflect.TypeOf((*MockNetwork)(nil).RemovePeerToAddrBook), peer)
}

// SetBus mocks base method.
func (m *MockNetwork) SetBus(arg0 modules.Bus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBus", arg0)
}

// SetBus indicates an expected call of SetBus.
func (mr *MockNetworkMockRecorder) SetBus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBus", reflect.TypeOf((*MockNetwork)(nil).SetBus), arg0)
}
