// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: block_cons_temp.proto

package typespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockConsTemp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeader       *BlockHeaderConsTemp `protobuf:"bytes,1,opt,name=BlockHeader,proto3" json:"BlockHeader,omitempty"`
	Transactions      []*Transaction       `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	ConsensusEvidence []*Evidence          `protobuf:"bytes,3,rep,name=ConsensusEvidence,proto3" json:"ConsensusEvidence,omitempty"`
}

func (x *BlockConsTemp) Reset() {
	*x = BlockConsTemp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_cons_temp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockConsTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockConsTemp) ProtoMessage() {}

func (x *BlockConsTemp) ProtoReflect() protoreflect.Message {
	mi := &file_block_cons_temp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockConsTemp.ProtoReflect.Descriptor instead.
func (*BlockConsTemp) Descriptor() ([]byte, []int) {
	return file_block_cons_temp_proto_rawDescGZIP(), []int{0}
}

func (x *BlockConsTemp) GetBlockHeader() *BlockHeaderConsTemp {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *BlockConsTemp) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BlockConsTemp) GetConsensusEvidence() []*Evidence {
	if x != nil {
		return x.ConsensusEvidence
	}
	return nil
}

type BlockHeaderConsTemp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64  `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Hash   string `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	// string NetworkID = 3; // TODO: What is this for?
	Time   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"` // BFT Timestamp.
	NumTxs uint32                 `protobuf:"varint,5,opt,name=NumTxs,proto3" json:"NumTxs,omitempty"`
	// int64 TotalTxs = 6;  // TODO: What is the purpose of this relative to NumTxs?
	LastBlockHash     string `protobuf:"bytes,7,opt,name=LastBlockHash,proto3" json:"LastBlockHash,omitempty"`
	ProposerAddress   []byte `protobuf:"bytes,8,opt,name=ProposerAddress,proto3" json:"ProposerAddress,omitempty"`
	ProposerId        uint32 `protobuf:"varint,9,opt,name=ProposerId,proto3" json:"ProposerId,omitempty"`               // TODO: Same as the NodeId throughout the consensus module.
	QuorumCertificate []byte `protobuf:"bytes,10,opt,name=QuorumCertificate,proto3" json:"QuorumCertificate,omitempty"` // TODO: just a gob serialization of the go struct for now, but switch to a proto.
}

func (x *BlockHeaderConsTemp) Reset() {
	*x = BlockHeaderConsTemp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_cons_temp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeaderConsTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeaderConsTemp) ProtoMessage() {}

func (x *BlockHeaderConsTemp) ProtoReflect() protoreflect.Message {
	mi := &file_block_cons_temp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeaderConsTemp.ProtoReflect.Descriptor instead.
func (*BlockHeaderConsTemp) Descriptor() ([]byte, []int) {
	return file_block_cons_temp_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeaderConsTemp) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeaderConsTemp) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlockHeaderConsTemp) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *BlockHeaderConsTemp) GetNumTxs() uint32 {
	if x != nil {
		return x.NumTxs
	}
	return 0
}

func (x *BlockHeaderConsTemp) GetLastBlockHash() string {
	if x != nil {
		return x.LastBlockHash
	}
	return ""
}

func (x *BlockHeaderConsTemp) GetProposerAddress() []byte {
	if x != nil {
		return x.ProposerAddress
	}
	return nil
}

func (x *BlockHeaderConsTemp) GetProposerId() uint32 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

func (x *BlockHeaderConsTemp) GetQuorumCertificate() []byte {
	if x != nil {
		return x.QuorumCertificate
	}
	return nil
}

// TODO: Move into a separate file.
type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_cons_temp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_block_cons_temp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_block_cons_temp_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// TODO: Move into a separate file.
type Evidence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_cons_temp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_block_cons_temp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_block_cons_temp_proto_rawDescGZIP(), []int{3}
}

func (x *Evidence) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_block_cons_temp_proto protoreflect.FileDescriptor

var file_block_cons_temp_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc7, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x73, 0x54, 0x65,
	0x6d, 0x70, 0x12, 0x3d, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73,
	0x54, 0x65, 0x6d, 0x70, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x37, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x11, 0x43, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x45,
	0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73,
	0x75, 0x73, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xa7, 0x02, 0x0a, 0x13, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x54, 0x65,
	0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2e,
	0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x54, 0x78, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x4e, 0x75, 0x6d, 0x54, 0x78, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4c,
	0x61, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x28, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d,
	0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x11, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x45, 0x76, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_block_cons_temp_proto_rawDescOnce sync.Once
	file_block_cons_temp_proto_rawDescData = file_block_cons_temp_proto_rawDesc
)

func file_block_cons_temp_proto_rawDescGZIP() []byte {
	file_block_cons_temp_proto_rawDescOnce.Do(func() {
		file_block_cons_temp_proto_rawDescData = protoimpl.X.CompressGZIP(file_block_cons_temp_proto_rawDescData)
	})
	return file_block_cons_temp_proto_rawDescData
}

var file_block_cons_temp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_block_cons_temp_proto_goTypes = []interface{}{
	(*BlockConsTemp)(nil),         // 0: pocket.BlockConsTemp
	(*BlockHeaderConsTemp)(nil),   // 1: pocket.BlockHeaderConsTemp
	(*Transaction)(nil),           // 2: pocket.Transaction
	(*Evidence)(nil),              // 3: pocket.Evidence
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_block_cons_temp_proto_depIdxs = []int32{
	1, // 0: pocket.BlockConsTemp.BlockHeader:type_name -> pocket.BlockHeaderConsTemp
	2, // 1: pocket.BlockConsTemp.Transactions:type_name -> pocket.Transaction
	3, // 2: pocket.BlockConsTemp.ConsensusEvidence:type_name -> pocket.Evidence
	4, // 3: pocket.BlockHeaderConsTemp.Time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_block_cons_temp_proto_init() }
func file_block_cons_temp_proto_init() {
	if File_block_cons_temp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_block_cons_temp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockConsTemp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_cons_temp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeaderConsTemp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_cons_temp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_cons_temp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Evidence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_block_cons_temp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_cons_temp_proto_goTypes,
		DependencyIndexes: file_block_cons_temp_proto_depIdxs,
		MessageInfos:      file_block_cons_temp_proto_msgTypes,
	}.Build()
	File_block_cons_temp_proto = out.File
	file_block_cons_temp_proto_rawDesc = nil
	file_block_cons_temp_proto_goTypes = nil
	file_block_cons_temp_proto_depIdxs = nil
}
