// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: message.proto

package typespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromAddress []byte `protobuf:"bytes,1,opt,name=FromAddress,proto3" json:"FromAddress,omitempty"`
	ToAddress   []byte `protobuf:"bytes,2,opt,name=ToAddress,proto3" json:"ToAddress,omitempty"`
	Amount      string `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MessageStakeServiceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey     []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Chains        []string `protobuf:"bytes,2,rep,name=Chains,proto3" json:"Chains,omitempty"`
	Amount        string   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ServiceURL    string   `protobuf:"bytes,4,opt,name=ServiceURL,proto3" json:"ServiceURL,omitempty"`
	OutputAddress []byte   `protobuf:"bytes,5,opt,name=OutputAddress,proto3" json:"OutputAddress,omitempty"`
	Signer        []byte   `protobuf:"bytes,6,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageStakeServiceNode) Reset() {
	*x = MessageStakeServiceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageStakeServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStakeServiceNode) ProtoMessage() {}

func (x *MessageStakeServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStakeServiceNode.ProtoReflect.Descriptor instead.
func (*MessageStakeServiceNode) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageStakeServiceNode) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MessageStakeServiceNode) GetChains() []string {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *MessageStakeServiceNode) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MessageStakeServiceNode) GetServiceURL() string {
	if x != nil {
		return x.ServiceURL
	}
	return ""
}

func (x *MessageStakeServiceNode) GetOutputAddress() []byte {
	if x != nil {
		return x.OutputAddress
	}
	return nil
}

func (x *MessageStakeServiceNode) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageEditStakeServiceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chains      []string `protobuf:"bytes,2,rep,name=Chains,proto3" json:"Chains,omitempty"`
	AmountToAdd string   `protobuf:"bytes,3,opt,name=AmountToAdd,proto3" json:"AmountToAdd,omitempty"`
	ServiceURL  string   `protobuf:"bytes,4,opt,name=ServiceURL,proto3" json:"ServiceURL,omitempty"`
	Signer      []byte   `protobuf:"bytes,5,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageEditStakeServiceNode) Reset() {
	*x = MessageEditStakeServiceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEditStakeServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditStakeServiceNode) ProtoMessage() {}

func (x *MessageEditStakeServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditStakeServiceNode.ProtoReflect.Descriptor instead.
func (*MessageEditStakeServiceNode) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageEditStakeServiceNode) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageEditStakeServiceNode) GetChains() []string {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *MessageEditStakeServiceNode) GetAmountToAdd() string {
	if x != nil {
		return x.AmountToAdd
	}
	return ""
}

func (x *MessageEditStakeServiceNode) GetServiceURL() string {
	if x != nil {
		return x.ServiceURL
	}
	return ""
}

func (x *MessageEditStakeServiceNode) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageUnstakeServiceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnstakeServiceNode) Reset() {
	*x = MessageUnstakeServiceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnstakeServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnstakeServiceNode) ProtoMessage() {}

func (x *MessageUnstakeServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnstakeServiceNode.ProtoReflect.Descriptor instead.
func (*MessageUnstakeServiceNode) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *MessageUnstakeServiceNode) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnstakeServiceNode) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageUnpauseServiceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnpauseServiceNode) Reset() {
	*x = MessageUnpauseServiceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnpauseServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnpauseServiceNode) ProtoMessage() {}

func (x *MessageUnpauseServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnpauseServiceNode.ProtoReflect.Descriptor instead.
func (*MessageUnpauseServiceNode) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageUnpauseServiceNode) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnpauseServiceNode) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessagePauseServiceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessagePauseServiceNode) Reset() {
	*x = MessagePauseServiceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePauseServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePauseServiceNode) ProtoMessage() {}

func (x *MessagePauseServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePauseServiceNode.ProtoReflect.Descriptor instead.
func (*MessagePauseServiceNode) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *MessagePauseServiceNode) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessagePauseServiceNode) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageStakeApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey     []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Chains        []string `protobuf:"bytes,2,rep,name=Chains,proto3" json:"Chains,omitempty"`
	Amount        string   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	OutputAddress []byte   `protobuf:"bytes,4,opt,name=OutputAddress,proto3" json:"OutputAddress,omitempty"`
	Signer        []byte   `protobuf:"bytes,5,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageStakeApp) Reset() {
	*x = MessageStakeApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageStakeApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStakeApp) ProtoMessage() {}

func (x *MessageStakeApp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStakeApp.ProtoReflect.Descriptor instead.
func (*MessageStakeApp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageStakeApp) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MessageStakeApp) GetChains() []string {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *MessageStakeApp) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MessageStakeApp) GetOutputAddress() []byte {
	if x != nil {
		return x.OutputAddress
	}
	return nil
}

func (x *MessageStakeApp) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageEditStakeApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chains      []string `protobuf:"bytes,2,rep,name=Chains,proto3" json:"Chains,omitempty"`
	AmountToAdd string   `protobuf:"bytes,3,opt,name=AmountToAdd,proto3" json:"AmountToAdd,omitempty"`
	Signer      []byte   `protobuf:"bytes,4,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageEditStakeApp) Reset() {
	*x = MessageEditStakeApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEditStakeApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditStakeApp) ProtoMessage() {}

func (x *MessageEditStakeApp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditStakeApp.ProtoReflect.Descriptor instead.
func (*MessageEditStakeApp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *MessageEditStakeApp) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageEditStakeApp) GetChains() []string {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *MessageEditStakeApp) GetAmountToAdd() string {
	if x != nil {
		return x.AmountToAdd
	}
	return ""
}

func (x *MessageEditStakeApp) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageUnstakeApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnstakeApp) Reset() {
	*x = MessageUnstakeApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnstakeApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnstakeApp) ProtoMessage() {}

func (x *MessageUnstakeApp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnstakeApp.ProtoReflect.Descriptor instead.
func (*MessageUnstakeApp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *MessageUnstakeApp) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnstakeApp) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageUnpauseApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnpauseApp) Reset() {
	*x = MessageUnpauseApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnpauseApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnpauseApp) ProtoMessage() {}

func (x *MessageUnpauseApp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnpauseApp.ProtoReflect.Descriptor instead.
func (*MessageUnpauseApp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *MessageUnpauseApp) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnpauseApp) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessagePauseApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessagePauseApp) Reset() {
	*x = MessagePauseApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePauseApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePauseApp) ProtoMessage() {}

func (x *MessagePauseApp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePauseApp.ProtoReflect.Descriptor instead.
func (*MessagePauseApp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *MessagePauseApp) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessagePauseApp) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageStakeValidator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey     []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Amount        string `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ServiceURL    string `protobuf:"bytes,3,opt,name=ServiceURL,proto3" json:"ServiceURL,omitempty"`
	OutputAddress []byte `protobuf:"bytes,4,opt,name=OutputAddress,proto3" json:"OutputAddress,omitempty"`
	Signer        []byte `protobuf:"bytes,5,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageStakeValidator) Reset() {
	*x = MessageStakeValidator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageStakeValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStakeValidator) ProtoMessage() {}

func (x *MessageStakeValidator) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStakeValidator.ProtoReflect.Descriptor instead.
func (*MessageStakeValidator) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *MessageStakeValidator) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MessageStakeValidator) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MessageStakeValidator) GetServiceURL() string {
	if x != nil {
		return x.ServiceURL
	}
	return ""
}

func (x *MessageStakeValidator) GetOutputAddress() []byte {
	if x != nil {
		return x.OutputAddress
	}
	return nil
}

func (x *MessageStakeValidator) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageEditStakeValidator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AmountToAdd string `protobuf:"bytes,2,opt,name=AmountToAdd,proto3" json:"AmountToAdd,omitempty"`
	ServiceURL  string `protobuf:"bytes,3,opt,name=ServiceURL,proto3" json:"ServiceURL,omitempty"`
	Signer      []byte `protobuf:"bytes,4,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageEditStakeValidator) Reset() {
	*x = MessageEditStakeValidator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEditStakeValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditStakeValidator) ProtoMessage() {}

func (x *MessageEditStakeValidator) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditStakeValidator.ProtoReflect.Descriptor instead.
func (*MessageEditStakeValidator) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *MessageEditStakeValidator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageEditStakeValidator) GetAmountToAdd() string {
	if x != nil {
		return x.AmountToAdd
	}
	return ""
}

func (x *MessageEditStakeValidator) GetServiceURL() string {
	if x != nil {
		return x.ServiceURL
	}
	return ""
}

func (x *MessageEditStakeValidator) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageUnstakeValidator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnstakeValidator) Reset() {
	*x = MessageUnstakeValidator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnstakeValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnstakeValidator) ProtoMessage() {}

func (x *MessageUnstakeValidator) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnstakeValidator.ProtoReflect.Descriptor instead.
func (*MessageUnstakeValidator) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *MessageUnstakeValidator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnstakeValidator) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageUnpauseValidator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnpauseValidator) Reset() {
	*x = MessageUnpauseValidator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnpauseValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnpauseValidator) ProtoMessage() {}

func (x *MessageUnpauseValidator) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnpauseValidator.ProtoReflect.Descriptor instead.
func (*MessageUnpauseValidator) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

func (x *MessageUnpauseValidator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnpauseValidator) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessagePauseValidator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessagePauseValidator) Reset() {
	*x = MessagePauseValidator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePauseValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePauseValidator) ProtoMessage() {}

func (x *MessagePauseValidator) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePauseValidator.ProtoReflect.Descriptor instead.
func (*MessagePauseValidator) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{15}
}

func (x *MessagePauseValidator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessagePauseValidator) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageFishermanPauseServiceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Reporter []byte `protobuf:"bytes,2,opt,name=Reporter,proto3" json:"Reporter,omitempty"`
	Signer   []byte `protobuf:"bytes,3,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageFishermanPauseServiceNode) Reset() {
	*x = MessageFishermanPauseServiceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFishermanPauseServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFishermanPauseServiceNode) ProtoMessage() {}

func (x *MessageFishermanPauseServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFishermanPauseServiceNode.ProtoReflect.Descriptor instead.
func (*MessageFishermanPauseServiceNode) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{16}
}

func (x *MessageFishermanPauseServiceNode) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageFishermanPauseServiceNode) GetReporter() []byte {
	if x != nil {
		return x.Reporter
	}
	return nil
}

func (x *MessageFishermanPauseServiceNode) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageStakeFisherman struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey     []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Chains        []string `protobuf:"bytes,2,rep,name=Chains,proto3" json:"Chains,omitempty"`
	Amount        string   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ServiceURL    string   `protobuf:"bytes,4,opt,name=ServiceURL,proto3" json:"ServiceURL,omitempty"`
	OutputAddress []byte   `protobuf:"bytes,5,opt,name=OutputAddress,proto3" json:"OutputAddress,omitempty"`
	Signer        []byte   `protobuf:"bytes,6,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageStakeFisherman) Reset() {
	*x = MessageStakeFisherman{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageStakeFisherman) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStakeFisherman) ProtoMessage() {}

func (x *MessageStakeFisherman) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStakeFisherman.ProtoReflect.Descriptor instead.
func (*MessageStakeFisherman) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{17}
}

func (x *MessageStakeFisherman) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MessageStakeFisherman) GetChains() []string {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *MessageStakeFisherman) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MessageStakeFisherman) GetServiceURL() string {
	if x != nil {
		return x.ServiceURL
	}
	return ""
}

func (x *MessageStakeFisherman) GetOutputAddress() []byte {
	if x != nil {
		return x.OutputAddress
	}
	return nil
}

func (x *MessageStakeFisherman) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageEditStakeFisherman struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chains      []string `protobuf:"bytes,2,rep,name=Chains,proto3" json:"Chains,omitempty"`
	AmountToAdd string   `protobuf:"bytes,3,opt,name=AmountToAdd,proto3" json:"AmountToAdd,omitempty"`
	ServiceURL  string   `protobuf:"bytes,4,opt,name=ServiceURL,proto3" json:"ServiceURL,omitempty"`
	Signer      []byte   `protobuf:"bytes,5,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageEditStakeFisherman) Reset() {
	*x = MessageEditStakeFisherman{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEditStakeFisherman) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditStakeFisherman) ProtoMessage() {}

func (x *MessageEditStakeFisherman) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditStakeFisherman.ProtoReflect.Descriptor instead.
func (*MessageEditStakeFisherman) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{18}
}

func (x *MessageEditStakeFisherman) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageEditStakeFisherman) GetChains() []string {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *MessageEditStakeFisherman) GetAmountToAdd() string {
	if x != nil {
		return x.AmountToAdd
	}
	return ""
}

func (x *MessageEditStakeFisherman) GetServiceURL() string {
	if x != nil {
		return x.ServiceURL
	}
	return ""
}

func (x *MessageEditStakeFisherman) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageUnstakeFisherman struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnstakeFisherman) Reset() {
	*x = MessageUnstakeFisherman{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnstakeFisherman) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnstakeFisherman) ProtoMessage() {}

func (x *MessageUnstakeFisherman) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnstakeFisherman.ProtoReflect.Descriptor instead.
func (*MessageUnstakeFisherman) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{19}
}

func (x *MessageUnstakeFisherman) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnstakeFisherman) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageTestScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionHeader   *SessionHeader         `protobuf:"bytes,1,opt,name=SessionHeader,proto3" json:"SessionHeader,omitempty"`
	FirstSampleTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=FirstSampleTime,proto3" json:"FirstSampleTime,omitempty"`
	NumberOfSamples uint32                 `protobuf:"varint,3,opt,name=NumberOfSamples,proto3" json:"NumberOfSamples,omitempty"`
	NullIndicies    []uint32               `protobuf:"varint,4,rep,packed,name=NullIndicies,proto3" json:"NullIndicies,omitempty"`
}

func (x *MessageTestScore) Reset() {
	*x = MessageTestScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTestScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTestScore) ProtoMessage() {}

func (x *MessageTestScore) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTestScore.ProtoReflect.Descriptor instead.
func (*MessageTestScore) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{20}
}

func (x *MessageTestScore) GetSessionHeader() *SessionHeader {
	if x != nil {
		return x.SessionHeader
	}
	return nil
}

func (x *MessageTestScore) GetFirstSampleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSampleTime
	}
	return nil
}

func (x *MessageTestScore) GetNumberOfSamples() uint32 {
	if x != nil {
		return x.NumberOfSamples
	}
	return 0
}

func (x *MessageTestScore) GetNullIndicies() []uint32 {
	if x != nil {
		return x.NullIndicies
	}
	return nil
}

type MessageProveTestScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionHeader *SessionHeader         `protobuf:"bytes,1,opt,name=SessionHeader,proto3" json:"SessionHeader,omitempty"`
	Leaf          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Leaf,proto3" json:"Leaf,omitempty"`
}

func (x *MessageProveTestScore) Reset() {
	*x = MessageProveTestScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageProveTestScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProveTestScore) ProtoMessage() {}

func (x *MessageProveTestScore) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProveTestScore.ProtoReflect.Descriptor instead.
func (*MessageProveTestScore) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{21}
}

func (x *MessageProveTestScore) GetSessionHeader() *SessionHeader {
	if x != nil {
		return x.SessionHeader
	}
	return nil
}

func (x *MessageProveTestScore) GetLeaf() *timestamppb.Timestamp {
	if x != nil {
		return x.Leaf
	}
	return nil
}

type MessageUnpauseFisherman struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessageUnpauseFisherman) Reset() {
	*x = MessageUnpauseFisherman{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUnpauseFisherman) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnpauseFisherman) ProtoMessage() {}

func (x *MessageUnpauseFisherman) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnpauseFisherman.ProtoReflect.Descriptor instead.
func (*MessageUnpauseFisherman) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{22}
}

func (x *MessageUnpauseFisherman) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageUnpauseFisherman) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessagePauseFisherman struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signer  []byte `protobuf:"bytes,2,opt,name=Signer,proto3,oneof" json:"Signer,omitempty"`
}

func (x *MessagePauseFisherman) Reset() {
	*x = MessagePauseFisherman{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePauseFisherman) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePauseFisherman) ProtoMessage() {}

func (x *MessagePauseFisherman) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePauseFisherman.ProtoReflect.Descriptor instead.
func (*MessagePauseFisherman) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{23}
}

func (x *MessagePauseFisherman) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessagePauseFisherman) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type MessageChangeParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer         []byte     `protobuf:"bytes,1,opt,name=Signer,proto3" json:"Signer,omitempty"`
	Owner          []byte     `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ParameterKey   string     `protobuf:"bytes,3,opt,name=ParameterKey,proto3" json:"ParameterKey,omitempty"`
	ParameterValue *anypb.Any `protobuf:"bytes,4,opt,name=ParameterValue,proto3" json:"ParameterValue,omitempty"`
}

func (x *MessageChangeParameter) Reset() {
	*x = MessageChangeParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChangeParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChangeParameter) ProtoMessage() {}

func (x *MessageChangeParameter) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChangeParameter.ProtoReflect.Descriptor instead.
func (*MessageChangeParameter) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{24}
}

func (x *MessageChangeParameter) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

func (x *MessageChangeParameter) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *MessageChangeParameter) GetParameterKey() string {
	if x != nil {
		return x.ParameterKey
	}
	return ""
}

func (x *MessageChangeParameter) GetParameterValue() *anypb.Any {
	if x != nil {
		return x.ParameterValue
	}
	return nil
}

type MessageDoubleSign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoteA           *Vote  `protobuf:"bytes,1,opt,name=VoteA,proto3" json:"VoteA,omitempty"`
	VoteB           *Vote  `protobuf:"bytes,2,opt,name=VoteB,proto3" json:"VoteB,omitempty"`
	ReporterAddress []byte `protobuf:"bytes,3,opt,name=ReporterAddress,proto3,oneof" json:"ReporterAddress,omitempty"`
}

func (x *MessageDoubleSign) Reset() {
	*x = MessageDoubleSign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageDoubleSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDoubleSign) ProtoMessage() {}

func (x *MessageDoubleSign) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDoubleSign.ProtoReflect.Descriptor instead.
func (*MessageDoubleSign) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{25}
}

func (x *MessageDoubleSign) GetVoteA() *Vote {
	if x != nil {
		return x.VoteA
	}
	return nil
}

func (x *MessageDoubleSign) GetVoteB() *Vote {
	if x != nil {
		return x.VoteB
	}
	return nil
}

func (x *MessageDoubleSign) GetReporterAddress() []byte {
	if x != nil {
		return x.ReporterAddress
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x74, 0x79, 0x70, 0x65, 0x73, 0x70, 0x62, 0x1a, 0x0a, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x65, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xd5, 0x01, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c,
	0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0xb9,
	0x01, 0x0a, 0x1b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x64, 0x69, 0x74, 0x53, 0x74,
	0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x41,
	0x64, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55,
	0x52, 0x4c, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x19, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x19, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0xad, 0x01, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x41, 0x70, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x91, 0x01, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x45, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x41, 0x70, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64,
	0x64, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x55, 0x0a, 0x11, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x41, 0x70, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x22, 0x55, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x70, 0x61, 0x75,
	0x73, 0x65, 0x41, 0x70, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x41, 0x70, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0xbb, 0x01, 0x0a,
	0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x24, 0x0a, 0x0d,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x9f, 0x01, 0x0a, 0x19, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x6f, 0x41, 0x64, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55,
	0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x55, 0x52, 0x4c, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x17,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x17, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b,
	0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x59, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x22, 0x80, 0x01, 0x0a, 0x20, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x50, 0x61, 0x75, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x06,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x22, 0xd3, 0x01, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x6b, 0x65, 0x46, 0x69, 0x73, 0x68, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x24, 0x0a, 0x0d,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0xb7, 0x01, 0x0a, 0x19, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x46,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x1b, 0x0a, 0x06,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55,
	0x6e, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x46, 0x69, 0x73, 0x68, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x22, 0xe4, 0x01, 0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x73,
	0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0f, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x4e, 0x75, 0x6c, 0x6c,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x65, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x73, 0x74, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x2e, 0x0a, 0x04, 0x4c, 0x65, 0x61, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x4c, 0x65, 0x61, 0x66,
	0x22, 0x5b, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x70, 0x61, 0x75,
	0x73, 0x65, 0x46, 0x69, 0x73, 0x68, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x59, 0x0a,
	0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x46, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0xa8, 0x01, 0x0a, 0x16, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x3c, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x0e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x23, 0x0a, 0x05, 0x56, 0x6f, 0x74,
	0x65, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x70, 0x62, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x41, 0x12, 0x23,
	0x0a, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x05, 0x56, 0x6f,
	0x74, 0x65, 0x42, 0x12, 0x2d, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0f,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x88,
	0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_message_proto_goTypes = []interface{}{
	(*MessageSend)(nil),                      // 0: typespb.MessageSend
	(*MessageStakeServiceNode)(nil),          // 1: typespb.MessageStakeServiceNode
	(*MessageEditStakeServiceNode)(nil),      // 2: typespb.MessageEditStakeServiceNode
	(*MessageUnstakeServiceNode)(nil),        // 3: typespb.MessageUnstakeServiceNode
	(*MessageUnpauseServiceNode)(nil),        // 4: typespb.MessageUnpauseServiceNode
	(*MessagePauseServiceNode)(nil),          // 5: typespb.MessagePauseServiceNode
	(*MessageStakeApp)(nil),                  // 6: typespb.MessageStakeApp
	(*MessageEditStakeApp)(nil),              // 7: typespb.MessageEditStakeApp
	(*MessageUnstakeApp)(nil),                // 8: typespb.MessageUnstakeApp
	(*MessageUnpauseApp)(nil),                // 9: typespb.MessageUnpauseApp
	(*MessagePauseApp)(nil),                  // 10: typespb.MessagePauseApp
	(*MessageStakeValidator)(nil),            // 11: typespb.MessageStakeValidator
	(*MessageEditStakeValidator)(nil),        // 12: typespb.MessageEditStakeValidator
	(*MessageUnstakeValidator)(nil),          // 13: typespb.MessageUnstakeValidator
	(*MessageUnpauseValidator)(nil),          // 14: typespb.MessageUnpauseValidator
	(*MessagePauseValidator)(nil),            // 15: typespb.MessagePauseValidator
	(*MessageFishermanPauseServiceNode)(nil), // 16: typespb.MessageFishermanPauseServiceNode
	(*MessageStakeFisherman)(nil),            // 17: typespb.MessageStakeFisherman
	(*MessageEditStakeFisherman)(nil),        // 18: typespb.MessageEditStakeFisherman
	(*MessageUnstakeFisherman)(nil),          // 19: typespb.MessageUnstakeFisherman
	(*MessageTestScore)(nil),                 // 20: typespb.MessageTestScore
	(*MessageProveTestScore)(nil),            // 21: typespb.MessageProveTestScore
	(*MessageUnpauseFisherman)(nil),          // 22: typespb.MessageUnpauseFisherman
	(*MessagePauseFisherman)(nil),            // 23: typespb.MessagePauseFisherman
	(*MessageChangeParameter)(nil),           // 24: typespb.MessageChangeParameter
	(*MessageDoubleSign)(nil),                // 25: typespb.MessageDoubleSign
	(*SessionHeader)(nil),                    // 26: typespb.SessionHeader
	(*timestamppb.Timestamp)(nil),            // 27: google.protobuf.Timestamp
	(*anypb.Any)(nil),                        // 28: google.protobuf.Any
	(*Vote)(nil),                             // 29: typespb.Vote
}
var file_message_proto_depIdxs = []int32{
	26, // 0: typespb.MessageTestScore.SessionHeader:type_name -> typespb.SessionHeader
	27, // 1: typespb.MessageTestScore.FirstSampleTime:type_name -> google.protobuf.Timestamp
	26, // 2: typespb.MessageProveTestScore.SessionHeader:type_name -> typespb.SessionHeader
	27, // 3: typespb.MessageProveTestScore.Leaf:type_name -> google.protobuf.Timestamp
	28, // 4: typespb.MessageChangeParameter.ParameterValue:type_name -> google.protobuf.Any
	29, // 5: typespb.MessageDoubleSign.VoteA:type_name -> typespb.Vote
	29, // 6: typespb.MessageDoubleSign.VoteB:type_name -> typespb.Vote
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_vote_proto_init()
	file_session_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageStakeServiceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEditStakeServiceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnstakeServiceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnpauseServiceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePauseServiceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageStakeApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEditStakeApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnstakeApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnpauseApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePauseApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageStakeValidator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEditStakeValidator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnstakeValidator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnpauseValidator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePauseValidator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFishermanPauseServiceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageStakeFisherman); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEditStakeFisherman); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnstakeFisherman); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTestScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageProveTestScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUnpauseFisherman); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePauseFisherman); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageChangeParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageDoubleSign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[15].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[16].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[17].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[18].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[19].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[22].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[23].OneofWrappers = []interface{}{}
	file_message_proto_msgTypes[25].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
