// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: transaction_indexer.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultTxResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx            []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`                                    // The bytes of the indexed transaction
	Height        int64  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`                           // The block height at which the transaction was included
	Index         int32  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`                             // The order (i.e. position within a block) where the proposer included the transaction
	ResultCode    int32  `protobuf:"varint,4,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"` // INVESTIGATE(andrew): look into having a `utility.Code` enum for this
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                              // INVESTIGATE(andrew): look into having a `utility.Error` enum for this
	SignerAddr    string `protobuf:"bytes,6,opt,name=signer_addr,json=signerAddr,proto3" json:"signer_addr,omitempty"`
	RecipientAddr string `protobuf:"bytes,7,opt,name=recipient_addr,json=recipientAddr,proto3" json:"recipient_addr,omitempty"`
	MessageType   string `protobuf:"bytes,8,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // CONSOLIDATE(M4): Once the message types are well defined and stable, consolidate them into an enum
}

func (x *DefaultTxResult) Reset() {
	*x = DefaultTxResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_indexer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTxResult) ProtoMessage() {}

func (x *DefaultTxResult) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_indexer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTxResult.ProtoReflect.Descriptor instead.
func (*DefaultTxResult) Descriptor() ([]byte, []int) {
	return file_transaction_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultTxResult) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *DefaultTxResult) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DefaultTxResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DefaultTxResult) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *DefaultTxResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DefaultTxResult) GetSignerAddr() string {
	if x != nil {
		return x.SignerAddr
	}
	return ""
}

func (x *DefaultTxResult) GetRecipientAddr() string {
	if x != nil {
		return x.RecipientAddr
	}
	return ""
}

func (x *DefaultTxResult) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

var File_transaction_indexer_proto protoreflect.FileDescriptor

var file_transaction_indexer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x22, 0xf1, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54,
	0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x25, 0x0a,
	0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6b, 0x74, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_indexer_proto_rawDescOnce sync.Once
	file_transaction_indexer_proto_rawDescData = file_transaction_indexer_proto_rawDesc
)

func file_transaction_indexer_proto_rawDescGZIP() []byte {
	file_transaction_indexer_proto_rawDescOnce.Do(func() {
		file_transaction_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_indexer_proto_rawDescData)
	})
	return file_transaction_indexer_proto_rawDescData
}

var file_transaction_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_indexer_proto_goTypes = []interface{}{
	(*DefaultTxResult)(nil), // 0: shared.DefaultTxResult
}
var file_transaction_indexer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_indexer_proto_init() }
func file_transaction_indexer_proto_init() {
	if File_transaction_indexer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transaction_indexer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTxResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_indexer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_indexer_proto_goTypes,
		DependencyIndexes: file_transaction_indexer_proto_depIdxs,
		MessageInfos:      file_transaction_indexer_proto_msgTypes,
	}.Build()
	File_transaction_indexer_proto = out.File
	file_transaction_indexer_proto_rawDesc = nil
	file_transaction_indexer_proto_goTypes = nil
	file_transaction_indexer_proto_depIdxs = nil
}
