name: Publish docs to Wiki

on:
  push:
    branches:
      - main # 1. When changes are merged to the main branch
    paths:
      - '**/*.md' # 2. It detects changes to Markdowns files in the repository

env: # 3. Set variables which the Python script uses for git commands
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # TODO_IN_THIS_COMMIT: provision repo secret through Pocket account
  USER_NAME: <user_name>
  USER_EMAIL: <user_email>
  OWNER: ${{ github.event.repository.owner.name }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  publish_docs_to_wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate and push Wiki
      run: | # 4. Runs a python script that uploads md files to Pocket Github Wiki
        python tools/wiki_sync.py
